test = {   'name': 'q3_4',
    'points': 1,
    'suites': [   {   'cases': [   {   'code': '>>> # Looks like you multiplied and subtracted in the wrong order.;\n>>> sum(celsius_max_temperatures) != 356705.0\nTrue',
                                       'hidden': False,
                                       'locked': False},
                                   {'code': '>>> sum(celsius_max_temperatures) == 1280677.0\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> len(celsius_max_temperatures) == 65000\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> celsius_max_temperatures.item(2003) == 20.0\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
