test = {   'name': 'q2_1_5',
    'points': 1,
    'suites': [   {   'cases': [   {'code': ">>> sum(['thriller' == most_common('Genre', close_movies.take(range(k))) for k in range(1, 5, 1)]) == 4\nTrue", 'hidden': False, 'locked': False},
                                   {   'code': ">>> [most_common('Genre', close_movies.take(range(4, k, -1))) for k in range(3, -1, -1)] == ['comedy', 'comedy', 'comedy', 'thriller']\nTrue",
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
