test = {   'name': 'q2_3',
    'points': 1,
    'suites': [   {   'cases': [   {   'code': '>>> # Double check that your salary_range function is correct;\n>>> salary_range(make_array(5, 1, 20, 1000)) == 999\nTrue',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> set(["department", "assistant professor", "associate professor", "lecturer", "professor"]) == set(department_ranges.labels)\nTrue',
                                       'hidden': False,
                                       'locked': False},
                                   {'code': '>>> sum(department_ranges.column(1)) == 2976273.0\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
